cvm-version: 0.7.5
cpus: 32
gpus: 8
memory: 524288

models:
  - name: "deepseek-v4-pro"
    repo: "deepseek-ai/DeepSeek-V4-Pro@5e74e6987d2007a261efc812d357ae75f9b8263a"
    mpk: "78bfe1473bb0ba0430b62822c7088e54014ef5c72b9dcc79aa1907f3bb451064_864744366080_35b772d4-2c2f-5c1f-a373-aa8d6db5ee04"

containers:
  - name: "deepseek-v4-pro"
    image: "vllm/vllm-openai:deepseekv4-cu130@sha256:2e05966d05579729137714d16035f0cb3b9f0fc1586fbd009753868ee9afc68b"
    runtime: nvidia
    gpus: all
    ipc: host
    env:
      - VLLM_ENGINE_READY_TIMEOUT_S: "3600"
    command: [
      "--model", "/tinfoil/mpk/mpk-78bfe1473bb0ba0430b62822c7088e54014ef5c72b9dcc79aa1907f3bb451064",
      "--trust-remote-code",
      "--kv-cache-dtype", "fp8",
      "--block-size", "256",
      "--enable-expert-parallel",
      "--data-parallel-size", "8",
      "--max-model-len", "800000",
      "--gpu-memory-utilization", "0.95",
      "--max-num-seqs", "512",
      "--max-num-batched-tokens", "512",
      "--no-enable-flashinfer-autotune",
      "--compilation-config", "{\"mode\": 0, \"cudagraph_mode\": \"FULL_DECODE_ONLY\"}",
      "--tokenizer-mode", "deepseek_v4",
      "--tool-call-parser", "deepseek_v4",
      "--enable-auto-tool-choice",
      "--reasoning-parser", "deepseek_v4",
      "--served-model-name", "deepseek-v4-pro",
      "--port", "8001"
    ]

shim:
  upstream-port: 8001
  authenticated: true
  authenticated-endpoints:
    - /v1/chat/completions
    - /v1/responses
  paths:
    - /v1/chat/completions
    - /v1/models
    - /v1/responses
    - /metrics
    - /health
