cvm-version: 0.7.5
cpus: 64
gpus: 8
memory: 524288

models:
  - name: "deepseek-v4-pro"
    repo: "deepseek-ai/DeepSeek-V4-Pro@0366e4e064385807ea86b088a5c6c878ff23343b"
    mpk: "4f5329f8b153498c9979d7ca3e0508af4ee2ebff19843b6f1a551af3df8b4ba6_864744366080_d8f50012-fffb-5715-962f-f9f405f9cf86"

containers:
  - name: "deepseek-v4-pro"
    image: "vllm/vllm-openai:deepseekv4-cu130@sha256:694f31f2d673a4d5dbbca4820f6d96dd09b2ddc74ccc868b677b89422e7ac2f8"
    runtime: nvidia
    gpus: all
    ipc: host
    env:
      - VLLM_ENGINE_READY_TIMEOUT_S: "3600"
    command: [
      "--model", "/tinfoil/mpk/mpk-4f5329f8b153498c9979d7ca3e0508af4ee2ebff19843b6f1a551af3df8b4ba6",
      "--trust-remote-code",
      "--kv-cache-dtype", "fp8",
      "--block-size", "256",
      "--enable-expert-parallel",
      "--data-parallel-size", "8",
      "--max-model-len", "800000",
      "--gpu-memory-utilization", "0.95",
      "--max-num-seqs", "512",
      "--max-num-batched-tokens", "512",
      "--no-enable-flashinfer-autotune",
      "--compilation-config", "{\"mode\": 0, \"cudagraph_mode\": \"FULL_DECODE_ONLY\"}",
      "--tokenizer-mode", "deepseek_v4",
      "--tool-call-parser", "deepseek_v4",
      "--enable-auto-tool-choice",
      "--reasoning-parser", "deepseek_v4",
      "--served-model-name", "deepseek-v4-pro",
      "--port", "8001"
    ]

shim:
  upstream-port: 8001
  authenticated: true
  authenticated-endpoints:
    - /v1/chat/completions
    - /v1/responses
  paths:
    - /v1/chat/completions
    - /v1/models
    - /v1/responses
    - /metrics
    - /health
